CLASS LHC_ZR_1029FLIGHT DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR Zr1029flight
        RESULT result,

      checkSemanticKey FOR VALIDATE ON SAVE
            IMPORTING keys FOR Zr1029flight~checkSemanticKey.
ENDCLASS.

CLASS LHC_ZR_1029FLIGHT IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.

  METHOD checkSemanticKey.
  ENDMETHOD.

ENDCLASS.
