CLASS LHC_ZR_S4D400ACONN000 DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR ZrS4d400aconn000
        RESULT result,

      CheckSemanticKey FOR VALIDATE ON SAVE
            IMPORTING keys FOR ZrS4d400aconn000~CheckSemanticKey. " Alias de Behaviour Definition ZrS4d400aconn000
ENDCLASS.

CLASS LHC_ZR_S4D400ACONN000 IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.
  METHOD CheckSemanticKey.
  ENDMETHOD.

ENDCLASS.
